name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: searchable_test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: true
      matrix:
        php: [ 7.2, 7.3, 7.4, 8.0 ]
        stability: [ prefer-lowest, prefer-stable ]
        laravel: [ ^6.15, ^7.0, ^8.0 ]
        include:
          - laravel: ^6.15
            testbench: 4.*
          - laravel: ^7.0
            testbench: 5.*
          - laravel: ^8.0
            testbench: 6.*
        exclude:
          - laravel: ^7.0
            php: 7.2
          - laravel: ^8.0
            php: 7.2

    name: PHP ${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Install legacy factories for Laravel 8
        if: ${{ matrix.laravel == '^8.0' }}
        run: |
          composer require laravel/legacy-factories --dev --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress --update-with-all-dependencies

      - name: Install legacy faker for php and laravel < 8
        if: ${{ matrix.php != 8.0 && matrix.laravel != '^8.0' && matrix.stability == 'prefer-lowest' }}
        run: |
          composer require fzaninotto/faker:^1.9 --dev --prefer-dist --no-interaction --no-progress --update-with-all-dependencies

      - name: Bump mockery for PHP 8
        if: ${{ matrix.php == 8.0 }}
        run: |
          composer require mockery/mockery:^1.4.2 --dev --prefer-dist --no-interaction --no-progress --update-with-all-dependencies

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USERNAME: root
          DB_PASSWORD: ''
